Get http://localhost:4000/user-api/getusers

###
GET http://localhost:4000/user-api/getuser/id

###
POST http://localhost:4000/user-api/create-user

###
PUT http://localhost:4000/user-api/update-user

###
DELETE http://localhost:4000/user-api/remove-user


# to deal with product apis

###
GET http://localhost:4000/product-api/getproducts

###
GET http://localhost:4000/product-api/getproduct/3

###
POST http://localhost:4000/product-api/create-product
Content-Type: application/json

{
    "productId":3,
    "productName":"Laptop",
    "brand":"Lenovo",
    "price":55000
}

###
PUT http://localhost:4000/product-api/update-product
Content-Type: application/json

{
    "productId":3,
    "productName":"Laptop",
    "brand":"HP",
    "price":49999
}

###
DELETE http://localhost:4000/product-api/remove-product/3